
CREATE TABLE Users
(
 ID int PRIMARY KEY IDENTITY,
 FullName NVARCHAR(250) not null,
 Email NVARCHAR(50),
 PhoneNumber NVARCHAR (20),
 BirthDate DATE,
 PasswordHash NVARCHAR(MAX),

 Active bit DEFAULT (0),
 CreatedAt DATETIME2 DEFAULT GETDATE(),
 UpdatedAt DATETIME2 DEFAULT GETDATE(),
)