CREATE TABLE Categories
(
 Id int PRIMARY KEY IDENTITY,
 Name NVARCHAR(250) NOT NULL,
 Type NVARCHAR(100),
 Icon NVARCHAR(10),
 UserId int NOT NULL,

 Active bit DEFAULT (0),
 CreatedAt DATETIME2 DEFAULT GETDATE(),
 UpdatedAt DATETIME2 DEFAULT GETDATE(),

 CONSTRAINT PK_Categories_Users FOREIGN KEY (UserId) REFERENCES Users(Id),

)