CREATE TABLE Reminders
(
 Id INT PRIMARY KEY IDENTITY(1,1),
 UserId INT NOT NULL,
 CategoryId INT NOT NULL,
 Title NVARCHAR(250) NOT NULL,
 Amount DECIMAL(18, 2) NOT NULL,
 RepeatCycle NVARCHAR(20) NOT NULL,
 NextRun DATETIME2 NOT NULL,
 Note NVARCHAR(500),

 Active bit DEFAULT (0),
 CreatedAt DATETIME2 DEFAULT GETDATE(),
 UpdatedAt DATETIME2 DEFAULT GETDATE(),

 CONSTRAINT FK_Reminders_Users FOREIGN KEY (UserId) REFERENCES Users(Id),
 CONSTRAINT FK_Reminders_Categories FOREIGN KEY (CategoryId) REFERENCES Categories(Id)
)